name: Python Package using Conda
permissions:
  contents: write
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel, main ]

jobs:
  build-linux:
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: devel
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Install dependencies
      run: |
        conda install numpy scipy h5py pandas xarray hatchling tqdm
        python -m pip install --upgrade pip
        pip install .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          channels: conda-forge
      - name: Install dependencies
        run: |
          conda install hatchling 
          python -m pip install --upgrade pip
          pip install pytest pytest-cov obspy
          pip install .
      - name: test
        run: |
          cd test
          pytest -v --cov=pytomoatt --cov-report=xml
      - name: Upload to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
